### ISSUE TITLE
Docker Daemon Exception

### ISSUE THREAD

**Issue by schneidermatic** [error418/tirolesa#6]
docker logs tirolesa
/opt/tirolesa/node_modules/passport-oauth2/lib/strategy.js:82
  if (!options.clientID) { throw new TypeError('OAuth2Strategy requires a clientID option'); }
                           ^

TypeError: OAuth2Strategy requires a clientID option
    at Strategy.OAuth2Strategy (/opt/tirolesa/node_modules/passport-oauth2/lib/strategy.js:82:34)
    at new Strategy (/opt/tirolesa/node_modules/passport-github2/lib/strategy.js:61:18)
    at Object.configure [as configureOAuth] (/opt/tirolesa/server/passport-oauth.js:34:18)
    at Object.<anonymous> (/opt/tirolesa/server/tirolesa-server.js:13:20)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)

**Comment by error418** [comment]
This error is thrown when passport-github2 is initialized with missing mandatory parameters. In this case `clientID` and the `secret` are not configured via container environment variable or configuration property.

Following things need to be implemented

- [x] improve error message (done in PR #7)
- [ ] improve documentation of configuration parameters

**Comment by schneidermatic** [comment]
But this kind of exception should not lead to a fragile container bootstrapping. A better approach would be to handle this kind of exception an to give the user the ability to provide the information via gui at a later time.
